name: spleeter
channels:
  - defaults
dependencies:
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - brotli-python=1.0.9
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - cffi=1.16.0
  - chardet=4.0.0
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - idna=3.7
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - ipykernel=6.28.0
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.4
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=7.4.9
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_fileid=0.9.0
  - jupyter_server_terminals=0.4.4
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab_pygments=0.2.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nltk=3.8.1
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - openssl=3.0.13
  - overrides=7.4.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.8.19
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=24.0.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=69.5.1
  - six=1.16.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.4
  - traitlets=5.7.1
  - typing_extensions=4.11.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - xz=5.4.6
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==0.30.1
      - anyio==3.7.1
      - arrow==1.3.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - audioread==3.0.1
      - boto3==1.34.120
      - botocore==1.34.120
      - bpemb==0.3.5
      - cachetools==5.3.3
      - charset-normalizer==3.3.2
      - click==7.1.2
      - commonmark==0.9.1
      - conllu==4.5.3
      - contourpy==1.1.1
      - cycler==0.12.1
      - deprecated==1.2.14
      - exceptiongroup==1.2.1
      - ffmpeg-python==0.2.0
      - filelock==3.14.0
      - flair==0.13.1
      - flatbuffers==24.3.25
      - fonttools==4.53.0
      - fqdn==1.5.1
      - fsspec==2024.5.0
      - ftfy==6.2.0
      - future==1.0.0
      - gast==0.4.0
      - gdown==5.2.0
      - gensim==4.3.2
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.64.0
      - h11==0.14.0
      - h2==4.1.0
      - h5py==3.11.0
      - hpack==4.0.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.23.3
      - hyperframe==6.0.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - isoduration==20.11.0
      - janome==0.5.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonpointer==2.4
      - jupyter-lsp==2.2.5
      - jupyterlab==4.2.1
      - jupyterlab-server==2.27.2
      - jupyterlab-vim==4.1.3
      - keras==2.13.1
      - kiwisolver==1.4.5
      - langdetect==1.0.9
      - libclang==18.1.1
      - librosa==0.8.1
      - llvmlite==0.38.1
      - lxml==5.2.2
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - more-itertools==10.2.0
      - mpld3==0.5.10
      - mpmath==1.3.0
      - networkx==3.1
      - norbert==0.2.1
      - numba==0.55.2
      - numpy==1.22.4
      - oauthlib==3.2.2
      - openai-whisper==20231117
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==1.5.3
      - pillow==10.3.0
      - platformdirs==2.6.2
      - pluggy==1.5.0
      - pocketsphinx==5.0.3
      - pooch==1.8.1
      - pptree==3.1
      - protobuf==3.20.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydub==0.25.1
      - pyparsing==3.1.2
      - pyscript==0.2.5
      - pytorch-revgrad==0.2.0
      - pytube==15.0.0
      - regex==2024.5.15
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rfc3986==1.5.0
      - rich==12.6.0
      - rich-click==1.8.2
      - rsa==4.9
      - s3transfer==0.10.1
      - safetensors==0.4.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - segtok==1.5.11
      - semver==3.0.2
      - sentencepiece==0.2.0
      - smart-open==7.0.4
      - sniffio==1.3.1
      - sounddevice==0.4.7
      - soundfile==0.12.1
      - speechrecognition==3.10.4
      - spleeter==2.3.2
      - sqlitedict==2.1.0
      - sympy==1.12.1
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-macos==2.13.0
      - tensorflow-metal==1.0.1
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - torch==2.3.0
      - transformer-smaller-training-vocab==0.4.0
      - transformers==4.41.2
      - typer==0.4.2
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.5.0
      - uri-template==1.3.0
      - urllib3==1.26.18
      - wcwidth==0.2.13
      - webcolors==1.13
      - werkzeug==3.0.3
      - wikipedia-api==0.6.0
      - wrapt==1.16.0
      - zipp==3.19.0
